CREATE TABLE IF NOT EXISTS `wp_abcinfosend` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(255) NOT NULL  COMMENT '标题',
`author`  varchar(255) NOT NULL  DEFAULT '和蔼的木Q技术支持' COMMENT '内容作者',
`sort`  int(10) NOT NULL  DEFAULT 100 COMMENT '排序值',
`token`  varchar(255) NOT NULL  COMMENT '公众号标识',
`thumb_media_id`  varchar(255) NOT NULL  COMMENT '缩约图id',
`content_source_url`  varchar(255) NOT NULL  COMMENT '信息内容外链接',
`content`  text NOT NULL  COMMENT '内容',
`digest`  text NOT NULL  COMMENT '简短描述',
`show_cover_pic`  char(10) NOT NULL  DEFAULT 1 COMMENT '是否显示封面',
`thumbimg`  int(10) UNSIGNED NOT NULL  COMMENT '缩略图',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('abcinfosend','ABC认证服务号图文信息群发','0','','1','{"1":["title","thumbimg","thumb_media_id","author","sort","digest","content","content_source_url"]}','1:基础','','','','','thumbimg:缩约图\r\ntitle:标题\r\nsort:排序号\r\nauthor:内容作者\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','','','1406169976','1406605709','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(255) NOT NULL','string','','','1','','0','1','1','1406171114','1406171114','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('author','内容作者','varchar(255) NOT NULL','string','和蔼的木Q技术支持','图文信息的作者','1','','0','1','1','1406171075','1406171075','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序值','int(10) NOT NULL','num','100','值越小排序越靠前','1','','0','1','1','1406170855','1406170855','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','公众号标识','varchar(255) NOT NULL','string','','','0','','0','1','1','1406196455','1406170780','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('thumb_media_id','缩约图id','varchar(255) NOT NULL','string','','微信公众平台上的图片ID，可通过上传文件生成','1','','0','1','1','1406170997','1406170997','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content_source_url','信息内容外链接','varchar(255) NOT NULL','string','','如无可不填','1','','0','0','1','1406171156','1406171156','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','内容','text NOT NULL','editor','','','1','','0','1','1','1406171190','1406171190','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('digest','简短描述','text NOT NULL','textarea','','可不填','1','','0','0','1','1406171228','1406171228','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('show_cover_pic','是否显示封面','char(10) NOT NULL','radio','1','','4','1:显示\r\n0:不显示','0','1','1','1406171435','1406171368','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('thumbimg','缩略图','int(10) UNSIGNED NOT NULL','picture','','','1','','0','1','1','1406171609','1406171609','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;